In [1]:
import numpy as np

In [2]:
#array slicing
x=np.arange(10)

In [3]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
x[2:8:2]

array([2, 4, 6])

In [10]:
x[:3]

array([0, 1, 2])

In [11]:
x[3:]

array([3, 4, 5, 6, 7, 8, 9])

In [14]:
x[3:9]#creating a sub-array of a single dimension array

array([3, 4, 5, 6, 7, 8])

In [21]:
x1=np.random.randint(6, size=(2,3,4))
x1[:2,:3]

array([[[3, 3, 0, 0],
        [1, 2, 2, 2],
        [0, 0, 4, 1]],

       [[5, 2, 0, 0],
        [1, 2, 5, 0],
        [1, 5, 5, 1]]])

In [29]:
#reshaping arrays
np.arange(1,17).reshape((4,4))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])